# MODBUS INPUTS REGISTER ADDRESSES
INPUT_POS_GIR       = 0x00      # FLOAT
INPUT_POS_ELE       = 0x02      # FLOAT
INPUT_AZIMUTE       = 0x04      # FLOAT 
INPUT_ZENITE        = 0x06      # FLOAT
INPUT_GENERATION 	= 0x08      # FLOAT  
INPUT_TEMP          = 0x0A      # FLOAT
INPUT_PRESURE       = 0x0C      # FLOAT
INPUT_SENS_CONF_GIR = 0x0E      # FLOAT
INPUT_SENS_CONF_ELE = 0x10      # FLOAT
INPUT_YEAR          = 0x12      # INT
INPUT_MONTH         = 0x13      # INT
INPUT_DAY           = 0x14      # INT
INPUT_HOUR          = 0x15      # INT
INPUT_MINUTE        = 0x16      # INT
INPUT_SECOND        = 0x17      # INT

# MODBUS HOLDING REGISTER ADDRESSES
HR_PV_GIR           = 0x00      # FLOAT
HR_KP_GIR           = 0x02      # FLOAT
HR_KI_GIR           = 0x04      # FLOAT
HR_KD_GIR           = 0x06      # FLOAT
HR_AZIMUTE          = 0x08      # FLOAT
HR_PV_ELE           = 0x0A      # FLOAT
HR_KP_ELE           = 0x0C      # FLOAT
HR_KI_ELE           = 0x0E      # FLOAT
HR_KD_ELE           = 0x10      # FLOAT
HR_ALTITUDE         = 0x12      # FLOAT
HR_LATITUDE         = 0x14      # FLOAT
HR_LONGITUDE        = 0x16      # FLOAT
HR_STATE            = 0x18      # INT
HR_YEAR             = 0x19      # INT
HR_MONTH            = 0x1A      # INT
HR_DAY              = 0x1B      # INT
HR_HOUR             = 0x1C      # INT
HR_MINUTE           = 0x1D      # INT
HR_SECOND           = 0x1E      # INT

# MODBUS DISCRETES REGISTER ADDRESSES
DISCRETE_FAIL       = 0x00      # BIT
DISCRETE_POWER      = 0x01      # BIT
DISCRETE_TIME       = 0x02      # BIT
DISCRETE_GPS        = 0x03      # BIT

# MODBUS COILS REGISTER ADDRESSES
COIL_POWER          = 0x00      # BIT    
COIL_LED            = 0x01      # BIT
COIL_M_GIR          = 0x02      # BIT
COIL_M_ELE          = 0x03      # BIT
COIL_LEDR           = 0x04      # BIT    
COIL_LEDG           = 0x05      # BIT    
COIL_LEDB           = 0x06      # BIT
COIL_SYNC_DATE      = 0x07      # BIT
