from libs.sweetalert.animation.failure_icon import FailureAnimation
from libs.sweetalert.animation.others_icon import OthersAnimation
from libs.sweetalert.animation.success_icon import SuccessAnimation